---
  - hosts:
      - tag_Name_prod_server
    become: yes
    gather_facts: yes
    tasks:
      - name: Write welcome message profile.d file
        ansible.builtin.template:
          src: welcome_message.j2
          dest: /etc/profile.d/welcome_message.sh
          owner: root
          group: root
          mode: '0644'

      - name: STARTING DOCKER
        ansible.builtin.shell: sudo systemctl start docker

      - name: COPY APP CODE TO REMOTE SERVER
        ansible.builtin.git:
          repo: https://github.com/olaniyikolawole744/devops-penultimante-project.git
          dest: /tmp/project
          separate_git_dir: /tmp/projectbakup2

      - name: LOG IN TO DOCKERHUB
        docker_login:
          registry_url: https://registry.hub.docker.com
          username: "{{ dockerhubusername }}"
          password: "{{ dockerhubpassword }}"
          reauthorize: yes

      - name: BUILD AND PUSH APP IMAGE TO DOCKERHUB
        docker_image:
          build:
            path: /tmp/project/code
            dockerfile: Dockerfile
            pull: yes
          source: build
          push: yes
          name: registry.hub.docker.com/olaniyikolawole744/direction-prod
          tag: latest

      - name: PULL APP IMAGE FROM DOCKERHUB
        docker_image:
          name: olaniyikolawole744/direction-prod
          tag: latest
          source: pull
          repository: registry.hub.docker.com/olaniyikolawole744/direction-prod

      - name: RUN APP APP CONTAINER
        ansible.builtin.shell: sudo  docker run -d -p 8080:8080 -e loginname=myname -e loginpass=mypass -e api_key=*****  olaniyikolawole744/direction-prod:latest
